In [4]:
import numpy as np

In [72]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print('a = ',a)

a =  [ 1  2  3  4  5  6  7  8  9 10]


In [74]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
b = np.zeros((3, 3), dtype=int)
print('B = ',b)

B =  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [76]:
#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
c = np.random.randint(1, 11, (5, 5))
print('C = ',c)

C =  [[ 9  1  9  4  7]
 [ 8  8  2 10  7]
 [ 7  3  8  2  4]
 [ 7  3  5  8  7]
 [ 2  3  3 10  4]]


In [78]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в 
#діапазоні від 0 до 1 та виведіть його значення.
d = np.random.random((4, 4))
print('D = ',d)

D =  [[0.64167261 0.21238363 0.56141555 0.03728706]
 [0.81059511 0.85822221 0.73962477 0.35790939]
 [0.54510541 0.15817901 0.61276333 0.48474706]
 [0.87638496 0.93538739 0.93139126 0.86050874]]


In [80]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 
#до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
e=np.random.randint(1,11,5)
print('e = ',e)
f=np.random.randint(1,11,5)
print('f = ',f)
print('e + f = ', e + f)
print('e - f = ', e - f)
print('e * f = ', e * f)

e =  [ 6 10  6  1  9]
f =  [3 7 9 1 4]
e + f =  [ 9 17 15  2 13]
e - f =  [ 3  3 -3  0  5]
e * f =  [18 70 54  1 36]


In [82]:
#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
h = np.random.random(7)
print('h = ', h)
i = np.random.random(7)
print('i = ', i)
print('(h⋅i) = ', np.dot(h, i))

h =  [0.67437248 0.02491663 0.04571165 0.40896244 0.06268301 0.05568964
 0.328531  ]
i =  [0.79822266 0.16568882 0.35244868 0.25492491 0.86456848 0.60801172
 0.95257692]
(h⋅i) =  1.0637982767821892


In [84]:
#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні
#від 1 до 10 та перемножте їх між собою.
j = np.random.randint(1, 11, (2, 2))
print('J = ', j)
k = np.random.randint(1, 11, (2, 3))
print('K = ', k)
result = np.dot(j, k)
print('J * K = ', result)

J =  [[ 7  2]
 [ 5 10]]
K =  [[ 1  1  1]
 [10 10  1]]
J * K =  [[ 27  27   9]
 [105 105  15]]


In [86]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні 
#від 1 до 10 та знайдіть її обернену матрицю.
l = np.random.randint(1, 11, (3, 3))
print('L = ', l)
l_inv = np.linalg.inv(l)
print('L^(-1) = ',l_inv)

L =  [[ 6  7  4]
 [ 5 10  2]
 [ 2  2  9]]
L^(-1) =  [[ 0.45502646 -0.29100529 -0.13756614]
 [-0.21693122  0.24338624  0.04232804]
 [-0.05291005  0.01058201  0.13227513]]


In [88]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні 
#від 0 до 1 та транспонуйте її.
k = np.random.random((4, 4))
print('K = ', k)
result = k.T
print('K^T = ',result)

K =  [[0.51490862 0.30047585 0.78413221 0.26142011]
 [0.14474549 0.50233515 0.15283313 0.28700807]
 [0.9189279  0.36573372 0.29758889 0.58990965]
 [0.64423614 0.50870496 0.9698922  0.96235574]]
K^T =  [[0.51490862 0.14474549 0.9189279  0.64423614]
 [0.30047585 0.50233515 0.36573372 0.50870496]
 [0.78413221 0.15283313 0.29758889 0.9698922 ]
 [0.26142011 0.28700807 0.58990965 0.96235574]]


In [90]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні
#від 1 до 10 та перемножте матрицю на вектор.
m = np.random.randint(1, 11, (3, 4))
print('M = ', m)
n=np.random.randint(1,11,4)
print('n = ',n)
result=np.dot(m, n)
print('M * n = ',result)

M =  [[ 7  9 10  2]
 [ 5 10  4  1]
 [ 9 10  4  7]]
n =  [ 9 10  1  3]
M * n =  [169 152 206]


In [92]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні
#від 0 до 1 та перемножте матрицю на вектор.
m = np.random.random((2, 3))
print('M = ', m)
n=np.random.random(3)
print('n = ',n)
result=np.dot(m, n)
print('M * n = ',result)

M =  [[0.68970815 0.34973499 0.14922573]
 [0.47495513 0.2289049  0.59031519]]
n =  [0.25442835 0.38030097 0.5742985 ]
M * n =  [0.39418598 0.54691193]


In [98]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та виконайте їхнє поелементне множення.
j = np.random.randint(1, 11, (2, 2))
print('J = ', j)
k = np.random.randint(1, 11, (2, 2))
print('K = ', k)
result = j*k
print('J * K = ', result)

J =  [[ 1  6]
 [ 4 10]]
K =  [[3 2]
 [3 8]]
J * K =  [[ 3 12]
 [12 80]]


In [100]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та знайдіть їх добуток.
j = np.random.randint(1, 11, (2, 2))
print('J = ', j)
k = np.random.randint(1, 11, (2, 2))
print('K = ', k)
result = np.dot(j, k)
print('J * K = ', result)

J =  [[5 9]
 [8 9]]
K =  [[3 5]
 [6 8]]
J * K =  [[ 69  97]
 [ 78 112]]


In [102]:
#14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні 
#від 1 до 100 та знайдіть суму елементів матриці.
j = np.random.randint(1, 101, (5, 5))
print('J = ', j)
print('sum = ', j.sum())

J =  [[39 62 62 25 88]
 [61 37 22 52 67]
 [40 35 59 79 73]
 [71 76 26 63 16]
 [78 70 50 67 90]]
sum =  1408


In [104]:
#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та знайдіть їхню різницю.
j = np.random.randint(1, 11, (4, 4))
print('J = ', j)
k = np.random.randint(1, 11, (4, 4))
print('K = ', k)
result = j- k
print('J - K = ', result)

J =  [[ 5  2  6  1]
 [ 3  8  8 10]
 [ 9  7  4  2]
 [ 6  8  1  2]]
K =  [[1 5 7 8]
 [1 7 2 3]
 [1 7 9 8]
 [8 8 6 4]]
J - K =  [[ 4 -3 -1 -7]
 [ 2  1  6  7]
 [ 8  0 -5 -6]
 [-2  0 -5 -2]]


In [16]:
#16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні 
#від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
m = np.random.random((3, 3))
print('M = ', m)
print('sum = ', (np.sum(m, axis=1)).reshape(-1, 1))

M =  [[0.97305132 0.68100641 0.24751065]
 [0.25492131 0.17629252 0.13425694]
 [0.49846994 0.23534945 0.426285  ]]
sum =  [[1.90156839]
 [0.56547077]
 [1.16010439]]


In [20]:
#17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
k = np.random.randint(1, 10, (3, 4))
print('K = ', k)
print('K ^ 2 = ', np.square(k))

K =  [[5 3 3 5]
 [2 2 3 3]
 [1 5 8 2]]
K ^ 2 =  [[25  9  9 25]
 [ 4  4  9  9]
 [ 1 25 64  4]]


In [22]:
#18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні 
#від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
n=np.random.randint(1,51,4)
print('n = ',n)
result=np.square(n)
print('n^2 = ',result)

n =  [32 49  1 32]
n^2 =  [1024 2401    1 1024]
